### ISSUE TITLE
Startup Error & DownstreamBridge Object

### ISSUE THREAD

**Issue by markhughes** [Phoenix616/ResourcepacksPlugins#7]
Hello! 

<s>To start off this is my startup error in bungee: http://pastebin.com/qT0y5S73</s>

I have a bungee network with multiple servers, in this situation my issue is between these three PaperSpigot servers:
- hub
- games
- survival

I have both BungeeResourcepacks installed and WorldResourcepacks.

Here are the configurations for all three: 
- Bungee config.yml: http://pastebin.com/05b0N1Cn
- Hub (and survival, they're the same) config.yml: http://pastebin.com/wG6dpbzq

The login to the games world and hub works fine (and survival too) - there are no errors thrown:

**games**

```
MarkehMe[/127.0.0.1:49068] logged in with entity id 4219045 at ([games]58.0, 75.0, 0.0)
[WorldResourcepacks] Send pack gameshub (http://xxxxx.net.au/textures/PlanetCraft-games-hub.zip) to MarkehMe
```

**hub**

```
UUID of player MarkehMe is d65e49f9-eb8f-4087-9004-c44216472905
MarkehMe[/180.181.100.94:48533] logged in with entity id 112 at ([hub]-48.65092091282099, 93.0, 0.41705329524693224)
[WorldResourcepacks] Send pack emptypack (http://xxxxx.net.au/textures/Empty.zip) to MarkehMe
```

However in my bungee console:

```
[INFO] [/180.xxx.xxx.xx:58119] <-> InitialHandler has connected
[INFO] [MarkehMe|/180.xxx.xxx.xx:58119] <-> ServerConnector [games] has connected
[SEVERE] [BungeeResourcepacks] Error while trying to get the UserConnection field from the DownstreamBridge object. Is the plugin up to date?
[INFO] [MarkehMe|/180.xxx.xxx.xx:58119] <-> ServerConnector [hub] has connected
[INFO] [/180.xxx.xxx.xx:58119|MarkehMe] <-> DownstreamBridge <-> [games] has disconnected
[SEVERE] [BungeeResourcepacks] Error while trying to get the UserConnection field from the DownstreamBridge object. Is the plugin up to date?
```

Now if I switch from my other worlds from say survival to hub (exact some configuration and texture pack as hub) it re-downloads the resource pack. Here is the log from my client: http://pastebin.com/4AAxpjKQ

Versions:
- Paper version git-Paper-832 (MC: 1.10.2) 
- Waterfall version git:Waterfall-Bootstrap:1.10-SNAPSHOT:6c059bb:47
- BungeeResourcepacks version 1.6.3
- WorldResourcepacks version 1.6.2 (build #111)

**Comment by Phoenix616** [comment]
### For the bungee startup error:

You are defined both, global and servers as an empty list [] where the plugin expects a configuration section. Just remove both keys if you don't want to configure anything there.

### For the error when trying to send the pack:

Which build of BungeeResourcepakcs are you running? Maybe you can try the latest one available [here](http://ci.minebench.de/job/ResourcepacksPlugins/) as I can't reproduce the issue. 

Also please note that Waterfall isn't officially supported and may have some incompatibilities with Bungee plugins that access internal stuff.

**Comment by MarkehMe** [comment]
The issue still exists with build #129 of the bukkit plugins but perhaps I also need to update the bungee plugins. I'll test that tonight.

**Comment by Phoenix616** [comment]
Yes, please try whether or not the errors on Bungee are being resolved by updating the Bungee plugin.

**Comment by MarkehMe** [comment]
I have updated the Bungee plugin and I'm still having issues

**Comment by Phoenix616** [comment]
Please provide all the versions of the plugins and servers used in your latest test. Also can you try it with just the Bungee plugin?

**Comment by MarkehMe** [comment]
I unfortunately have not had time to test (nor even log onto my minecraft server) but will get to this soon.

**Comment by Phoenix616** [comment]
Should not happen anymore nowadays.
